In [1]:
import numpy as np

In [11]:
array_a = np.array([1,2,3])

In [3]:
array_a

array([1, 2, 3])

In [4]:
array_b = np.array([[1],[2]])

In [5]:
array_b

array([[1],
       [2]])

In [6]:
matrix_c  = np.array([[1,2,3],[4,5,6]])
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

Broadcasting

In [12]:
np.add(array_a,matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

In [18]:
array_b + matrix_c


array([[2, 3, 4],
       [6, 7, 8]])

In [19]:
array_b


array([[1],
       [2]])

In [21]:
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
array_b + matrix_c

array([[2, 3, 4],
       [6, 7, 8]])

In [23]:
np.add(array_b,matrix_c)

array([[2, 3, 4],
       [6, 7, 8]])

Casting

In [25]:
np.add(array_b,matrix_c,dtype=np.float32)

array([[2., 3., 4.],
       [6., 7., 8.]], dtype=float32)