# NumPy DataTypes

In [1]:
import numpy as np

### 1. With the help of the <i> np.array() </i>function, create a 1-D array variable <i> array_hw_1 </i> with the numbers from 1 to 8 and display it on the screen.

In [2]:
array_1D = np.array([1,2,3,4,5,6,7,8])

### 2.Check its type, shape and size. 
<i> (<b>Hint </b>: "type" is a Python function, while "shape" and "size" are attributes of the array) </i>

In [3]:
type(array_1D)

numpy.ndarray

In [5]:
array_1D.shape

(8,)

In [6]:
array_1D.size

8

### 3. Now, create a 2x4 2-D array, <i> array_hw_2</i> with the same values & display it on screen. 

In [11]:
array_2D = np.array([[9,10,11,12],[13,14,15,16]])

### 4. Find its type, shape, and size. 

In [13]:
type(array_2D)

numpy.ndarray

In [14]:
array_2D.size

8

In [18]:
array_2D


array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 5. Use square brackets to create a 3-D array with the same values as <i> array_hw_2 </i> and display it on screen.

In [16]:
array_3D = np.array([[[1,2,3,4],[5,6,7,8]]])

### 6. Find its type, shape and size. 


In [19]:
type(array_3D)

numpy.ndarray

In [20]:
array_3D.shape

(1, 2, 4)

In [21]:
array_3D.size

8

### 7. Define a 2-D list <i> list_hw_1 </i> with the same values as <i> array_hw_2 </i>and display it on screen.

In [23]:
list_2D = [[1,2,3],[4,5,6]]
list_2D

[[1, 2, 3], [4, 5, 6]]

### 8. Find the length of this 2-D list. 

In [28]:
len(list_2D)

2

### 9. Fint the length of one of its sublists. 

In [30]:
list_2D[0]+list_2D[1]

[1, 2, 3, 4, 5, 6]

### 10. Verify its type. 

In [31]:
type(list_2D)

list

### 11. Use the <i>np.array()</i> function to create an array out of <i> list_hw_1</i> and display it on screen.

In [33]:
array_from_list = np.array(list_2D)
list_2D

[[1, 2, 3], [4, 5, 6]]

### 12. Create two more variables and display them on screen:
    A) A list which is the sum of the two sublists of list_hw_1;
    B) An array which is the sum of the two subarrays of array_hw_4;
    
    (Hint: Use indexing to refer to the different sub-lists/arrays)

In [34]:
print(list_2D[0] + list_2D[1])

[1, 2, 3, 4, 5, 6]


In [35]:
print(array_from_list[0]+array_from_list[1])

[5 7 9]


### 13. Find the square roots of all the elements in <i> array_sum </i>
   <i> (<b>Hint</b>: Use the np.sqrt() function)

In [38]:
np.sqrt(array_from_list)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### 13. Find the square roots of all the elements in <i> list_sum </i>
   <i> (<b>Hint</b>: Most NumPy functions are equipped to handle <b> lists </b>like ndarrays with the same shape)

In [39]:
np.sqrt(list_2D)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### 14. Use <i> np.genfromtxt() </i> to import the <i> "Lending-Company-Total-Price.csv" </i> file as strings and display its contents.
    You can open the file in a text editor like Notepad++ to check its delimiter. 

In [40]:
lending_company = np.genfromtxt("/Users/jakeabella/DataScience-GIT/datascience/resources/lending-co-LT.csv",
                              delimiter=',',
                              dtype=('int32','str','str','str','str','str','int32'))

### 15. Use the <i> skip_header </i> and <i> usecols </i> parameters to only take the numerical data from the file. Then, let's see how the inputs change if we alter the datatype argument to:

    A) The default (not specify it)
    B) 32-bit integers (np.int32)
    C) 32-bit floats (np.float32)
    D) 64-bit complex numbers (np.complex64)
    E) Unicode (np.unicode)
    F) Objects (np.object)
    G) None

In [41]:
lending_company

array([(  -1, '', '', '', '', '',    -1),
       (   1, '', '', '', '', '', 16600),
       (   2, '', '', '', '', '', 16600), ...,
       (1041, '', '', '', '', '', 16600),
       (1042, '', '', '', '', '', 15600),
       (1043, '', '', '', '', '', 16600)],
      dtype=[('f0', '<i4'), ('f1', '<U'), ('f2', '<U'), ('f3', '<U'), ('f4', '<U'), ('f5', '<U'), ('f6', '<i4')])

### 16. Setting the datatype to None means the function automatically chooses the datatype for each column of the text file, so let's see how this works for all the columns.

In [45]:
np.genfromtxt("/Users/jakeabella/DataScience-GIT/datascience/resources/lending-co-LT.csv",
                              delimiter=',')

array([[      nan,       nan,       nan, ...,       nan,       nan,
              nan],
       [1.000e+00,       nan,       nan, ...,       nan,       nan,
        1.660e+04],
       [2.000e+00,       nan,       nan, ...,       nan,       nan,
        1.660e+04],
       ...,
       [1.041e+03,       nan,       nan, ...,       nan,       nan,
        1.660e+04],
       [1.042e+03,       nan,       nan, ...,       nan,       nan,
        1.560e+04],
       [1.043e+03,       nan,       nan, ...,       nan,       nan,
        1.660e+04]])