In [2]:
import numpy as np

INDEXING


In [3]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

Specific Values

In [5]:
array_a[0]

array([1, 2, 3])

In [8]:
array_a[1,0] # this is the same as array_a[1][0]

4

In [9]:
array_a[1][0]

4

NEGATIVE ARRAYS

In [10]:
array_a[-1]

array([4, 5, 6])

In [11]:
array_a[-2]

array([1, 2, 3])

Assigning Values

In [25]:
array_a = np.array([[1,2,3],[4,5,6]])

In [16]:
array_a[0,2] = 8 #change # 123 element to 129 
array_a[0,2]

8

In [17]:
array_a

array([[1, 2, 8],
       [4, 5, 6]])

In [20]:
array_a[0] = 9 # assigning a singular value to a multi dimentional row will turn all elements on that row to the value you set
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [26]:
array_a[:,2]

array([3, 6])

In [27]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
array_b =np.array([1,2,3,4,5,6])

In [44]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
array_a[0:1]

array([[1, 2, 3]])

In [47]:
array_a[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
array_a[:,1]

array([2, 5])

## 

In [61]:
array_a[:,2]

array([3, 6])

In [62]:
array_a[:]=3

In [63]:
array_a

array([[3, 3, 3],
       [3, 3, 3]])

In [66]:
array_a[0] = ['24','25',0]

In [67]:
array_a

array([[24, 25,  0],
       [ 3,  3,  3]])

In [68]:
array_b = np.array([[1,2,3],[4,5,6]])

In [69]:
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
array_b +2

array([[3, 4, 5],
       [6, 7, 8]])

In [73]:
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
array_a

array([[ 3,  6,  9],
       [12, 15, 18]])

In [83]:
array_a = np.array([[3,6,9],[12,15,18]])

In [81]:
array_a +array_b

array([[ 4.,  8., 12.],
       [16., 20., 24.]])

In [87]:
array_a = np.array([[1,2,3],[4,5,6]],dtype=np.complex64)
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [92]:
array_a = np.array([[1,2,3],[4,5,6]],dtype=np.float16)
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [93]:
array_a = np.array([[1,2,3],[4,5,6]],dtype=np.bool_)
array_a

array([[ True,  True,  True],
       [ True,  True,  True]])

In [94]:
array_a = np.array([[1,2,3],[4,5,6]],dtype=np.single)
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)