In [9]:
import numpy as np


In [10]:
matrix_A = np.array([[1,2,3],[4,5,6]])

In [20]:
matrix_A[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
matrix_A[:111]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
matrix_C = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])

In [31]:
matrix_C

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [35]:
matrix_C[:] > 2

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [36]:
matrix_C[matrix_C[:]>2]

array([3, 6, 6, 7, 4, 4, 5, 3, 8])

In [37]:
#all even
matrix_C[matrix_C[:] % 2 ==0 ]

array([2, 0, 6, 6, 4, 4, 8, 0])

In [45]:
matrix_C[(matrix_C[:] % 2 == 0) & (matrix_C[:]>4)]

array([6, 6, 8])

Squeeze Function

In [46]:
matrix_D = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])

In [47]:
matrix_D

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [48]:
type(matrix_D[0,0])

numpy.int32

In [49]:
type(matrix_D[0:,0:1])

numpy.ndarray

In [54]:
matrix_D[0,0:1].shape

(1,)

In [53]:
matrix_D[0:1,0:1].shape

(1, 1)

In [60]:
matrix_D[0:1,0:1].shape

(1, 1)

In [65]:
matrix_D[0:1,0:2].squeeze().shape

(2,)