In [1]:
import numpy as np


In [6]:
array_a = np.array([1,2,3,4])

In [5]:
type(array_a)

numpy.ndarray

In [8]:
array_a


array([1, 2, 3, 4])

In [10]:
array_a.shape

(4,)

In [13]:
array_b = np.array([[7,8,9],[10,11,12]] )

In [14]:
array_b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [15]:
array_b.shape

(2, 3)

In [16]:
array_c = np.array(13)

In [17]:
type(array_c)

numpy.ndarray

In [19]:
print(array_c)

13


In [20]:
type(array_c)

numpy.ndarray

In [21]:
array_c.shape

()

In [23]:
array_d = np.array([1])

In [24]:
array_d

array([1])

In [25]:
type(array_d)

numpy.ndarray

In [26]:
array_d.shape

(1,)

# ARRAYS VS LIST


In [27]:
list_a = [[1,2,3],[4,5,6]]

In [28]:
len(list_a)

2

In [29]:
array_a = np.array(list_a)

In [30]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
list_a

[[1, 2, 3], [4, 5, 6]]

In [32]:
array_a.size

6

In [35]:
len(list_a)

2

In [38]:
array_a[1][2]

6

In [39]:
print(list_a[0] + list_a[1])

[1, 2, 3, 4, 5, 6]


In [40]:
print(array_a[0] + array_a[1])

[5 7 9]


In [41]:
import math
array_e = math.sqrt(array_a[1,0])

In [43]:
print(array_e)

2.0


In [44]:
array_a[1,0]

4