In [95]:
fileName = "/Users/jakeabella/UDM-DATASCIENCE 001/Data Analyst Course/files/sample.txt"


In [96]:
fileName


'/Users/jakeabella/UDM-DATASCIENCE 001/Data Analyst Course/files/sample.txt'

In [97]:
file = open(fileName, mode = 'r')

In [98]:
text = file.read()

In [99]:
file.closed

False

In [100]:
file.close()

In [101]:
text

'writing now\nwriting again'

In [102]:
with open(fileName,mode = 'r') as out_file:
     text = out_file.read();


In [103]:
text


'writing now\nwriting again'

In [104]:
with open(fileName,mode = 'w') as in_file:
    in_file.write("writing now\n")
    in_file.write('writing again')




In [105]:
text

'writing now\nwriting again'

In [107]:
csvFile = "/Users/jakeabella/UDM-DATASCIENCE 001/Data Analyst Course/files/Lending-company.csv"

In [109]:
import pandas as pd;


In [110]:
csvContents = pd.read_csv(csvFile)

In [111]:
type(csvContents)

pandas.core.frame.DataFrame

In [113]:
csvContents

LoanID     StringID    Product CustomerGender     Location    Region  \
0          1     LoanID_1  Product B         Female   Location 3  Region 2   
1          2     LoanID_2  Product D         Female   Location 6  Region 6   
2          3     LoanID_3  Product B           Male   Location 8  Region 3   
3          4     LoanID_4  Product A           Male  Location 26  Region 2   
4          5     LoanID_5  Product B         Female  Location 34  Region 3   
...      ...          ...        ...            ...          ...       ...   
1038    1039  LoanID_1039  Product B           Male  Location 73  Region 6   
1039    1040  LoanID_1040  Product A           Male  Location 82  Region 1   
1040    1041  LoanID_1041  Product A   NotSpecified  Location 11  Region 4   
1041    1042  LoanID_1042  Product B         Female  Location 26  Region 6   
1042    1043  LoanID_1043  Product A   NotSpecified  Location 94  Region 6   

      TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  \
0        17600.0  04/07/2018     2200         45          365       3221   
1            NaN  02/01/2019     2200         45          365       3161   
2        16600.0  08/12/2016     1000         45          365       2260   
3        17600.0         NaN     2200         45          365       3141   
4        21250.0  28/10/2017     2200         55          365       3570   
...          ...         ...      ...        ...          ...        ...   
1038     17300.0  29/12/2018     2200         45          365       3251   
1039         NaN  28/03/2018     2200         45          365       4090   
1040     17300.0  26/04/2018     2200         45          365       4051   
1041     16300.0  25/10/2016     1000         45          365       1930   
1042     17300.0  15/05/2019     2200         45          365       4451   

      AmtPaid60  AmtPaid360        LoanStatus  
0          4166       14621            Active  
1          4096       16041            Active  
2          3205       16340               NaN  
3          4166       16321            Active  
4          4745       14720            Active  
...         ...         ...               ...  
1038       4743       16617  Finished Payment  
1039       5582       16617  Finished Payment  
1040       5143       16617  Finished Payment  
1041       3462       15617  Finished Payment  
1042       4743       16617  Finished Payment  

[1043 rows x 15 columns]

In [117]:
import numpy as np

In [125]:
np_data = np.loadtxt("/Users/jakeabella/UDM-DATASCIENCE 001/Data Analyst Course/files/Lending-Company-Numeric-Data.csv",delimiter=",")

In [126]:
type(np_data)

numpy.ndarray

In [128]:
np_data

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [139]:
np.genfromtxt("/Users/jakeabella/UDM-DATASCIENCE 001/Data Analyst Course/files/Lending-Company-Numeric-Data-NAN.csv",delimiter=";", dtype= 'S')

array([[b'2000', b'40', b'365', b'3121', b'4241', b'13621'],
       [b'2000', b'40', b'365', b'3061', b'4171', b'15041'],
       [b'1000', b'40', b'365', b'2160', b'3280', b'15340'],
       ...,
       [b'', b'40', b'365', b'4201', b'5001', b'16600'],
       [b'1000', b'40', b'365', b'2080', b'3320', b'15600'],
       [b'2000', b'40', b'365', b'4601', b'4601', b'16600']], dtype='|S5')

In [152]:
col_5,col_0,col_1 = np.genfromtxt("/Users/jakeabella/UDM-DATASCIENCE 001/Data Analyst Course/files/Lending-Company-Numeric-Data-NAN.csv",delimiter=";",usecols=(5,0,1),skip_header=2,skip_footer=2,unpack=True)

In [153]:
col_5

array([15340., 15321., 13720., ..., 16600., 16600., 16600.])

In [154]:
col_0

array([1000., 2000., 2000., ..., 2000., 2000.,   nan])

In [156]:
col_1

array([40., 40., 50., ..., 40., 40., 40.])

In [151]:
np_data_selective

array([[15340.,  1000.,    40.],
       [15321.,  2000.,    40.],
       [13720.,  2000.,    50.],
       ...,
       [16600.,  2000.,    40.],
       [16600.,  2000.,    40.],
       [16600.,    nan,    40.]])

In [149]:
np_data_selective

array([[15340.,  1000.,    40.],
       [15321.,  2000.,    40.],
       [13720.,  2000.,    50.],
       ...,
       [16600.,    nan,    40.],
       [15600.,  1000.,    40.],
       [16600.,  2000.,    40.]])